#ifndef __DEVICE_ENUM_H__
#define __DEVICE_ENUM_H__

enum UART_FLOW_CTRL
{	FC_NONE,
	FC_SW,
	FC_HW,
	FC_MAX
};

enum UART_TYPE
{	UT_UART,
	UT_RS485,
	UT_VCOMM,
	UT_USB,
	//UT_BLE,
	UT_MAX
};

enum IOT_IF_SEL
{	IOT_IF_SEL_IOT1_UART,
	IOT_IF_SEL_IOT2_UART,
	IOT_IF_SEL_MK1_UART,
	IOT_IF_SEL_MK2_UART,
	IOT_IF_SEL_IOT1_USB,
	IOT_IF_SEL_IOT2_USB,
	IOT_IF_SEL_MK1_USB,
	IOT_IF_SEL_MK2_USB,
	IOT_IF_SEL_MK1_I2C,
	IOT_IF_SEL_MK2_I2C,
	IOT_IF_SEL_MK1_SPI,
	IOT_IF_SEL_MK2_SPI,
	IOT_IF_SEL_MAX
};

enum GPIO_TYPE
{	GPIO_TYPE_NO_CHANGE,
	GPIO_TYPE_INPUT,
	GPIO_TYPE_OUTPUT,
	GPIO_TYPE_POST_SET_OUTPUT,
	GPIO_TYPE_PRE_SET_OUTPUT,
	GPIO_TYPE_RTC_INPUT,
	GPIO_TYPE_RTC_OUTPUT,
	GPIO_TYPE_MAX
};

enum GPIO_PULLSEL
{	GPIO_PULLSEL_NONE,
	GPIO_PULLSEL_PULLHIGH,
	GPIO_PULLSEL_PULLLOW,
	GPIO_PULLSEL_MAX
};

enum CAMERA_FSM
{	CAMERA_FSM_PRE_INIT,
	CAMERA_FSM_IDLE,
	CAMERA_FSM_START,
	CAMERA_FSM_STOP,
	CAMERA_FSM_RESET,
	CAMERA_FSM_WAIT_RDY,
	CAMERA_FSM_CHG_RESOLUTION,
	CAMERA_FSM_CHG_QUALITY,
	CAMERA_FSM_CATCH_IMG,
	CAMERA_FSM_GET_IMG_SIZE,
	CAMERA_FSM_IR_CTRL_TURN_OFF,
	CAMERA_FSM_GET_IMG_RAW,
	CAMERA_FSM_WAIT_FOR_CHG_STS,
	CAMERA_FSM_MAX
};


enum EXT_DEV_MODEL
{	EXT_DEV_MODEL_NORMAL = -1,
	EXT_DEV_MODEL_OSA24G = 0,
	EXT_DEV_MODEL_OSA77G,
	EXT_DEV_MODEL_AVDS,
	EXT_DEV_MODEL_VW,
	EXT_DEV_MODEL_COMPOSITE_OSA24G,
	EXT_DEV_MODEL_COMPOSITE_SIEMENS,
	EXT_DEV_MODEL_CAMERA,
	EXT_DEV_MODEL_MAX
};


enum EXT_IF_CHANNEL
{	EXT_IF_CHANNEL_RS485_1,
	EXT_IF_CHANNEL_RS485_2,
	EXT_IF_CHANNEL_RS232,
	EXT_IF_CHANNEL_ETH,
	EXT_IF_CHANNEL_USB_HS,
	EXT_IF_CHANNEL_MAX
};

enum EXT_IF_PROTOCOL
{	EXT_IF_PROTO_NONE = 0,
	EXT_IF_PROTO_MODBUS,			//1
	EXT_IF_PROTO_DCON,				//2
	EXT_IF_PROTO_TOUCH_PAD,			//3
	EXT_IF_PROTO_AVDS_RADAR,		//4
	EXT_IF_PROTO_AR77_RADAR,		//5
	EXT_IF_PROTO_DISPLAY_PANEL,		//6
	EXT_IF_PROTO_CAMERA,			//7
	EXT_IF_PROTO_CONSOLE,			//8
	EXT_IF_PROTO_MAX
};

enum EXT_DEV_TYPE
{	//modbus
	EXT_DEV_TYPE_MODBUS_NORMAL,
	EXT_DEV_TYPE_MODBUS_OSA24G,
	EXT_DEV_TYPE_MODBUS_ANA_AUDIO,
	EXT_DEV_TYPE_MODBUS_SMR01,
	EXT_DEV_TYPE_MODBUS_SMR61_WL,
	EXT_DEV_TYPE_MODBUS_SMR61_RADAR,
	EXT_DEV_TYPE_MODBUS_SMR61_SET_IH,
	EXT_DEV_TYPE_MODBUS_SMR_GET_MODEL,
	EXT_DEV_TYPE_MODBUS_COMP_OSA_RADAR,
	EXT_DEV_TYPE_MODBUS_COMP_OSA_WLS,
	EXT_DEV_TYPE_MODBUS_COMP_SIEMENS_WLS,
	EXT_DEV_TYPE_MODBUS_VW_SENSOR,
	//radar
	EXT_DEV_TYPE_RADAR_AVDS,
	EXT_DEV_TYPE_RADAR_AR77,
	//DCON
	EXT_DEV_TYPE_DCON_NORMAL,
	EXT_DEV_TYPE_MAX
};

/*
*	RADAR define
*/

enum RADAR_FSM
{	RADAR_FSM_IDLE,
	RADAR_FSM_POWER_ON,
	RADAR_FSM_WAIT_POWER_READY,
	RADAR_FSM_ISSUE_CMD,
	RADAR_FSM_RECEIVE_DATA,
	RADAR_FSM_PARSER_DATA,
	RADAR_FSM_GET_PQ,
	RADAR_FSM_POWER_OFF,
	RADAR_FSM_WAIT_POWER_OFF_DONE,
	RADAR_FSM_SWITCH_RADAR,
	RADAR_FSM_RSP_TIMEOUT,
	RADAR_FSM_CALIBRATION,
	RADAR_FSM_RESTART,
	RADAR_FSM_MAX
};

enum AVDS_HW_PQ
{	AVDS_HW_PQ_DISTANCE,
	AVDS_HW_PQ_SNR,
	AVDS_HW_PQ_POWER,
	AVDS_HW_PQ_ANGLE,
	AVDS_HW_PQ_STATUS,
	//AVDS_HW_PQ_RESOLUTION,
	AVDS_HW_PQ_WL,
	AVDS_HW_PQ_TILT_DISTANCE,
	AVDS_HW_PQ_TILT_SNR,
	AVDS_HW_PQ_TILT_POWER,
	AVDS_HW_PQ_TILT_ANGLE,
	AVDS_HW_PQ_TILT_STATUS,
	//AVDS_HW_PQ_TILT_RESOLUTION,
	AVDS_HW_PQ_TILT_WL,
	AVDS_HW_PQ_MAX
};

enum DCON_DEV_FSM
{	DCON_DEV_FSM_IDLE,
	DCON_DEV_FSM_INIT,
	DCON_DEV_FSM_PWR_ON,
	DCON_DEV_FSM_PWR_ON_WAIT,
	DCON_DEV_FSM_POLLING_WAIT,
	DCON_DEV_FSM_SEND,
	DCON_DEV_FSM_RECV,
	//DCON_DEV_FSM_PROCESS,
	DCON_DEV_FSM_GET_HW_PQ,
	DCON_DEV_FSM_SET_SW_PQ,
	DCON_DEV_FSM_PWR_OFF,
	DCON_DEV_FSM_PWR_OFF_WAIT,
	DCON_DEV_FSM_MAX
};

enum MODBUS_MODE
{	MODBUS_MODE_CILENT,
	MODBUS_MODE_SERVER,
	MODBUS_MODE_MAX
};

enum MODBUS_RUN_FSM
{	MODBUS_RUN_FSM_IDLE,
	MODBUS_RUN_FSM_PREPARE,
	MODBUS_RUN_FSM_SEND,
	MODBUS_RUN_FSM_RECV,
	MODBUS_RUN_FSM_DONE,
	MODBUS_RUN_FSM_PWR_ON_PREPARE,
	MODBUS_RUN_FSM_MAX
};

enum MODBUS_DEV_FSM
{	MODBUS_DEV_FSM_IDLE,
	MODBUS_DEV_FSM_INIT,
	MODBUS_DEV_FSM_PWR_ON,
	MODBUS_DEV_FSM_PWR_ON_WAIT,
	MODBUS_DEV_FSM_POLLING_WAIT,
	MODBUS_DEV_FSM_PROCESS,
	MODBUS_DEV_FSM_GET_HW_PQ,
	MODBUS_DEV_FSM_SET_SW_PQ,
	MODBUS_DEV_FSM_PWR_OFF,
	MODBUS_DEV_FSM_PWR_OFF_WAIT,
	MODBUS_DEV_FSM_MAX
};

enum MODBUS_DATA_TYPE
{	MODBUS_DT_FLOAT = 11,
	MODBUS_DT_INT16,
	MODBUS_DT_INT32,
	MODBUS_DT_UINT16,
	MODBUS_DT_UINT32,
	MODBUS_DT_BOOL,
	MODBUS_DT_STRING,
	MODBUS_DT_MAX
};

/*
*	data order , data array, a, b, c, d
*/
enum MODBUS_DATA_ORDER
{	MODBUS_DO_dcba=1,
	MODBUS_DO_cdab,
	MODBUS_DO_badc,
	MODBUS_DO_abcd,
	MODBUS_DO_ab,
	MODBUS_DO_ba,
	MODBUS_DO_BOOL,
	MODBUS_DO_MAX
};

enum DCON_PARSER_TYPE
{	DCON_PARSER_TYPE_ASCII_TO_FLOAT = 8,
	DCON_PARSER_TYPE_HEX_ASCII_TO_UINT16,
	DCON_PARSER_TYPE_ASCII_TO_BOOL,
	DCON_PARSER_TYPE_HEX_ASCII_TO_BOOL,
	DCON_PARSER_TYPE_MAX
};

enum SENSOR_STRUCT_IDX
{	SENSOR_STRUCT_IDX_MODBUS_INST,
	SENSOR_STRUCT_IDX_HW_PQ,
	SENSOR_STRUCT_IDX_PROCESS_CTX,
	SENSOR_STRUCT_IDX_SENSOR_CTX,
	SENSOR_STRUCT_IDX_MAX
};

enum DEVICE_PWR_SRC
{	DEVICE_PWR_SRC_DO0,
	DEVICE_PWR_SRC_DO1,
	DEVICE_PWR_SRC_EXT,
	//DEVICE_PWR_SRC_5V,
	DEVICE_PWR_SRC_24V,
	DEVICE_PWR_SRC_MAX
};


enum DEVICE_POLLING_INTERVAL
{	DEVICE_POLLING_INTERVAL_CONTINUED,
	DEVICE_POLLING_INTERVAL_1_MIN,
	DEVICE_POLLING_INTERVAL_REC_TIME,
	DEVICE_POLLING_INTERVAL_MAX
};

enum DI_ID
{	DI_ID_0,
	DI_ID_1,
	DI_ID_2,
	DI_ID_3,
	DI_ID_MAX
};

enum DI_KEEP_ON_FSM
{	DI_KEEP_ON_FSM_IDLE,
	DI_KEEP_ON_FSM_KEEP_ON_PREPARE,
	DI_KEEP_ON_FSM_CHK_KEEP_ON,
	DI_KEEP_ON_FSM_KEEP_ON,
	DI_KEEP_ON_FSM_RELEASE_PREPARE,
	DI_KEEP_ON_FSM_RELEASE_WAIT,
	DI_KEEP_ON_FSM_RELEASE,
	DI_KEEP_ON_FSM_CHK_RELEASE_TIMER,
	DI_KEEP_ON_FSM_SOCKET_SEND_WAIT,
	DI_KEEP_ON_FSM_MAX
};

#endif