#ifndef __VOLT_SENSE_H__
#define __VOLT_SENSE_H__

#include "sensminiCfg.h"

#define ADC_FILTER_STD		0

#define ADC_RESOLUTION		12
#define	ADC_RESO_12BIT_VAL	0x03
#define ADC_RESO_10BIT_VAL	0x02
#define ADC_RESO_8BIT_VAL 	0x01
#define ADC_RESO_6BIT_VAL 	0x00

#define ADC_AVERAGE_COUNT	30
#define ADC_STD_COUNT		20

#define ADC_SAMPLING_TIME_EXTEND	255	//0~255
#define ADC_TRIG_DELAY_CNT			128	//0-255

#define I_LOAD_SENSOR_EADC_CH		12	//EADC CH2
#define I_SOLAR_SENSOR_EADC_CH		13	//EADC CH2
#define V_BAT_SENSOR_EADC_CH		6	//EADC CH1, CH2
#define V_SOLAR_SENSOR_EADC_CH		5	//EADC CH1, CH2

#define I_LOAD_SENSOR_EADC_SAMPLE_NO	3
#define I_SOLAR_SENSOR_EADC_SAMPLE_NO	4
#define V_BAT_SENSOR_EADC_SAMPLE_NO		5
#define V_SOLAR_SENSOR_EADC_SAMPLE_NO	6


#define SENS_ADC_SAMPLING_TIME_EXTEND	ADC_SAMPLING_TIME_EXTEND	//0
#define ENABLE_TRIGGER_DELAY	1


#if ADC_RESOLUTION == 10
#define ADC_RESOLUTION_VAL	ADC_RESO_10BIT_VAL
#elif ADC_RESOLUTION == 8
#define ADC_RESOLUTION_VAL	ADC_RESO_8BIT_VAL
#elif ADC_RESOLUTION == 6
#define ADC_RESOLUTION_VAL	ADC_RESO_6BIT_VAL
#else
#define ADC_RESOLUTION_VAL	ADC_RESO_12BIT_VAL
#endif

#define ADC_FULLSCALE		((1 << ADC_RESOLUTION)-1)

#define ADC_VREF				3.3f
#define BAT_R1					100.0f	//100.0f
#define BAT_R2					10.0f	//49.9f
#define R1						150.0f	//100.0f
#define	R2						10.0f	//10.0f
#define V_GAIN					((R1+R2)/R2)
#define V_GAIN_BAT				((BAT_R1+BAT_R2)/BAT_R2)
#define TO_VOLTAGE_SOLAR(a)		((ADC_VREF * V_GAIN * a)/ADC_FULLSCALE)
#define TO_VOLTAGE_BAT(a)		((ADC_VREF * V_GAIN_BAT * a)/ADC_FULLSCALE)

#define TO_VOLTAGE_SOLAR_I(a)	((ADC_VREF * a) / ADC_FULLSCALE)
#define TO_VOLTAGE_LOAD_I(a)	((ADC_VREF * a) / ADC_FULLSCALE)


#define DETECT_SOLAR_I		0
#define DETECT_LOAD_I		0

#if DETECT_SOLAR_I && DETECT_LOAD_I
	#define ALL_ADC_DONE	((1 << I_LOAD_SENSOR_EADC_SAMPLE_NO) | (1 << I_SOLAR_SENSOR_EADC_SAMPLE_NO) | (1 << V_BAT_SENSOR_EADC_SAMPLE_NO) | (1 << V_SOLAR_SENSOR_EADC_SAMPLE_NO))
#elif DETECT_SOLAR_I
	#define ALL_ADC_DONE	((1 << I_SOLAR_SENSOR_EADC_SAMPLE_NO) | (1 << V_BAT_SENSOR_EADC_SAMPLE_NO) | (1 << V_SOLAR_SENSOR_EADC_SAMPLE_NO))
#elif DETECT_LOAD_I
	#define ALL_ADC_DONE	((1 << I_LOAD_SENSOR_EADC_SAMPLE_NO)  | (1 << V_BAT_SENSOR_EADC_SAMPLE_NO) | (1 << V_SOLAR_SENSOR_EADC_SAMPLE_NO))
#else
	#define ALL_ADC_DONE	( (1 << V_BAT_SENSOR_EADC_SAMPLE_NO) | (1 << V_SOLAR_SENSOR_EADC_SAMPLE_NO))
#endif


extern void voltSenseInit(void);
extern void voltSenseStart(void);
extern void voltSenseCheck(void);

#endif
