#ifndef __FFS_CONFIG_H__
#define __FFS_CONFIG_H__

#define FILE_SYSTEM_INTERFACE_SD
#define FILE_SYSTEM_FS_EXFAT
#define FILE_SYSTEM_USE_LFN 3
#define FILE_SYSTEM_USE_MKFS
#define FILE_SYSTEM_NUM_LOGIC_VOL 1
#define FILE_SYSTEM_USE_STRFUNC 2
//#define FILE_SYSTEM_SET_FS_RPATH 0
#define FILE_SYSTEM_SET_FS_RPATH 1
#define FILE_SYSTEM_WORD_ACCESS

#define FILE_SYSTEM_USE_CHMOD

#endif
