#ifndef __MQTT_ENUM_H__
#define __MQTT_ENUM_H__


enum SENSTALK_MQTT_CMD_TYPE{	
  STK_READ_IOs,
  STK_READ_AI,
  STK_READ_DI,
  STK_READ_DO,
  STK_READ_RECS,
  STK_WRITE_DO,
  STK_READ_SYS,
  STK_CONNECT,
  STK_SLEEP,
  STK_READ_CFG,
  STK_WRITE_CFG,
  STK_REBOOT,
  STK_AUTOSEND,
  STK_SLEEP_AUTOSEND,
  //STK_FOTA_WAIT,
  STK_FOTA_ACK,
  STK_READ_L_CFG,
  STK_WRITE_L_CFG,
	IKW_MQTT_CMD_SETS,
	IKW_DATA_SYNC,
	SCFG_FOTA,
	SCFG_CFG,
	SCFG_CALIBRATION,
	SCFG_IM,
  MQTT_CMD_TYPE_MAX
};


enum MQTT_PLATFORM_ENUM
{	MQTT_SENSTALK_BROKER=0, 	//0
	MQTTS_SENSTALK_BROKER,		//1
	MQTTS_ANIOT_BROKER,				//2
	MQTTS_AZURE_BROKER,				//3
	MQTTS_AVNET_BROKER,				//4
	MQTT_THINGSBOARD_BROKER,	//5
	MQTTS_THINGSBOARD_BROKER,	//6
	MQTT_I_KNOW_WATER_BROKER,	//7
	MQTTS_I_KNOW_WATER_BROKER,	//8
	MQTT_SENSSEWER_BROKER,	//9
	MQTTS_SENSSEWER_BROKER,	//10
	MQTT_PLATFORM_MAX,
	SENSTALK_V2 = 99,
//#if SUPPORT_IOA_WEB_API
	IOA_WEB_API_PROTOCOL = 100,
	IOA_PLATFORM_MAX,
//#endif
#if YS_MQTT_BROKER
	MQTT_YS_BROKER  = 1000,
	MQTTS_YS_BROKER,
#endif
	NET_PROTOCOL_MAX
};

enum MQTT_CONN_TYPE_ENUM
{	MQTT_CONN_TYPE_WIRELESS,
	MQTT_CONN_TYPE_ETH,
	MQTT_CONN_TYPE_MAX
};

#endif

