#ifndef __NETWORK_CONFIG_H__
#define __NETWORK_CONFIG_H__


#define YS_MQTT_MDVPN_IP	"192.168.12.137"

#define SENS_DEFAULT_IP		0xC0A8FF01

#define SOCKET_T        	int32_t
#define MAX_WIRE_LAN_SOCK	(8)
#define SERV1_SOCK_IDX			0
#define SERV2_SOCK_IDX			1
#define IMAGE_SOCK_IDX			2

#define MOBILE_UART_BUFFER_SIZE			4096

#define IP_MAX_COMMAND_LEN	64	//include MDVPN Tag

#define NB_SEND_STR			"[A4-->NB]"
#define LTE_SEND_STR		"[A4-->LTE]"
#define WISUN_SEND_STR		"[A4-->WISUN]"
#define LORA_WAN_SEND_STR	"[A4-->LORA WAN]"
#define LORA_P2P_SEND_STR	"[A4-->LORA P2P]"

#define NB_RECV_STR			"[NB-->A4]"
#define LTE_RECV_STR		"[LTE-->A4]"
#define WISUN_RECV_STR		"[WISUN-->A4]"
#define LORA_WAN_RECV_STR	"[LORA WAN-->A4]"
#define LORA_P2P_RECV_STR	"[LORA P2P-->A4]"

#define NB_STATUS_STR		"[=NBIoT=]"
#define LTE_STATUS_STR		"[==4 G==]"
#define WISUN_STATUS_STR	"[=WISUN=]"
#define LORA_WAN_STATUS_STR	"[=LORA WAN=]"
#define LORA_P2P_STATUS_STR	"[=LORA P2P=]"

#define WAIT_STR_TYPE_SPECIFY	0x0000
#define WAIT_STR_TYPE_OK		0x0001

#define NB_OP_MODE_AUTO			0
#define NB_OP_MODE_MANUAL		1
#define NB_OP_MODE_DEREGISTER	2
#define NB_OP_MODE_SET_FORMAT	3

#define PSD_CFG_PARAM_TAG_APN		1
#define PSD_CFG_PARAM_TAG_USERNAME	2
#define PSD_CFG_PARAM_TAG_PASSWORD	3
#define PSD_CFG_PARAM_TAG_AUTH		6
#define PSD_CFG_PARAM_TAG_MAP_PROFILE_CID	100

#define L210_TCP_STS_INACTIVE		0
#define L210_TCP_STS_LISTEN			1
#define L210_TCP_STS_SYN_SENT		2
#define L210_TCP_STS_SYN_RCVD		3
#define L210_TCP_STS_ESTABILISHED	4
#define L210_TCP_STS_FIN_WAIT_1		5
#define L210_TCP_STS_FIN_WAIT_2		6
#define L210_TCP_STS_CLOSE_WAIT		7
#define L210_TCP_STS_CLOSING		8
#define L210_TCP_STS_LAST_ACK		9
#define L210_TCP_STS_TIME_WAIT		10


#define IGNORE_OTHER_AT_CMD_RSP		1
#define CHECK_OTHER_AT_CMD_RSP		0

#define HTTP_GET			0
#define HTTP_HEAD			1
#define HTTP_DELETE			2
#define HTTP_POST			0x80
#define HTTP_PUT			0x81

#define HTTP_URL_STR_MAX_LEN			128
#define HTTP_PATH_STR_MAX_LEN			128
#define HTTP_FILENAME_STR_MAX_LEN		32

#define HTTP_POST_STEP_IDLE 		0
#define HTTP_POST_STEP_RUNNING		1
#define HTTP_POST_STEP_WAIT			2
#define HTTP_POST_STEP_RETRY		3
#define HTTP_POST_STEP_PREPARE		0x40
#define HTTP_POST_RE_SEND			0x80
#define HTTP_POST_RE_SEND_MASK		0x7F

/*
* NETWORK INIT ERROR CODE
*/
#define NW_INIT_ERR_OK										0
#define NW_INIT_ERR_CONTINUE							1
#define NW_INIT_ERR_AT_RSP_TIMEOUT				-1
#define NW_INIT_ERR_RSP_OTHER_CMD					-2
#define NW_INIT_ERR_AT_INCORRECT_LENGTH		-4
#define NW_INIT_ERR_EMPTY_SIM							-5
#define NW_INIT_ERR_FSM_UNKNOWN						-6
#define NW_INIT_ERR_SYS_REBOOT						-7


#define GPRS_CLOCK_CHECK_TIMEOUT 			60000L
#define GPRS_CSQ_TIMEOUT  					80000L
#define GPRS_UREG_TIMEOUT 					100000L
#define GPRS_CSQ_SHORT_TIMEOUT				500L

#define MAX_CFG_ITEM	(3+SUPPORT_FOTA)


#define HTTP_CLI_RSP_PARSER_RESULT_OK	0
#define HTTP_CLI_RSP_PARSER_RESULT_INCOMPLETE_DATA	-2
#define HTTP_CLI_RSP_PARSER_RESULT_FAIL	-1
//#define HTTP_CLI_RSP_PARSER_RESULT_CONT	1

#define HTTP_POST_TIMEOUT_SECOND			(120000L)
#define HTTP_POST_TIMEOUT  					(30000L)

#endif
