#ifndef __NETWORK_ENUM_H__
#define __NETWORK_ENUM_H__

enum MOBILE_TYPE
{	MOBILE_TYPE_NONE,
	MOBILE_TYPE_L210,
	MOBILE_TYPE_R410,
	MOBILE_TYPE_N200,
	MOBILE_TYPE_ME310G,	//Telit CAT-M1
	MOBILE_TYPE_LE910C1,	//Telit LTE
	MOBILE_TYPE_AS923,
	MOBILE_TYPE_GPS_L76,
	MOBILE_TYPE_WI_SUN,
	MOBILE_TYPE_LORA_WAN,
	MOBILE_TYPE_LORA_P2P,
	MOBILE_TYPE_USB,
	MOBILE_TYPE_LE910C4,
	MOBILE_TYPE_LE910_WWX,
	MOBILE_TYPE_AUTO,
	MOBILE_TYPE_MAX
};

enum MOBILE_PROTOCOL
{	MOBILE_PROTOCOL_NORMAL,
	MOBILE_PROTOCOL_MODBUS,
	MOBILE_PROTOCOL_MAX
};

enum MOBILE_AT_TYPE
{	MOBILE_AT_TYPE_UBLOX,
	MOBILE_AT_TYPE_TELIT,
	MOBILE_AT_TYPE_MAX
};

enum MOBILE_CELL_TYPE
{	MOBILE_CELL_TYPE_LTE,
	MOBILE_CELL_TYPE_NBIOT,
	MOBILE_CELL_TYPE_MAX
};

enum SIM_TYPE
{	SIM_TYPE_LTE,
	SIM_TYPE_NB_AUTO,
	SIM_TYPE_CAT_M1,
	SIM_TYPE_NBIOT,
	SIM_TYPE_MAX
};

enum WL_INIT_STS
{	WL_INIT_STS_NONE, 
	WL_INIT_STS_SUCCESS,
	WL_INIT_STS_FAIL,
	WL_INIT_STS_RETRY,
	WL_INIT_STS_SWAP,
	WL_INIT_STS_MAX
};

/*enum UART_FLOW_CTRL
{	FC_NONE = 0,
	FC_SW,
	FC_HW,
	FC_MAX
};*/

enum WL_REGISTER_STS
{	WL_REG_STS_NOT_REGISTER = 0,
	WL_REG_STS_GPRS_2G,
	WL_REG_STS_EDGE_2G,
	WL_REG_STS_WCDMA_3G,
	WL_REG_STS_HSDPA_3G,
	WL_REG_STS_HSUPA_3G,
	WL_REG_STS_HSDPA_HSUPA,
	WL_REG_STS_LTE_4G,
	WL_REG_STS_GPRS_2G_1,
	WL_REG_STS_EDGE_2G_1,
	WL_REG_STS_LTE_CAT_NB_M1,
	WL_REG_STS_WAIT_READY_FAIL = 0x80,	//device not install or UART fail
	WL_REG_STS_UART_COMM_TIMEOUT_FAIL,
	WL_REG_STS_SIM_NOT_READY,
	WL_REG_STS_RE_INIT,
	WL_REG_STS_PPP_FAIL,
	WL_REG_STS_MAX
};

enum LTE_MDVPN_TYPE
{	LTE_MDVPN_TYPE_NONE,
	LTE_MDVPN_TYPE_SENSLINK_MDVPN,
	LTE_MDVPN_TYPE_OTHER_MDVPN,
	LTE_MDVPN_TYPE_MAX
};

enum NET_SEND_FSM
{	NET_SEND_FSM_IDLE,
	NET_SEND_FSM_SEND_GUID,				//IOA_GET_TOKEN
	NET_SEND_FSM_SEND_GUID_DONE,	//IOA_GET_TOKEN_DONE
	NET_SEND_FSM_SEND_FIRST_PQ,
	NET_SEND_FSM_SEND_PQ,
	NET_SEND_FSM_SEND_PQ_TRIG,
	NET_SEND_FSM_CHK_HIST,
	NET_SEND_FSM_SEND_HIST,
	NET_SEND_FSM_SEND_HIST_TRIG,
	//NET_SEND_FSM_SEND_PQ_DONE,
	NET_SEND_FSM_MAX
};

enum XMIT_PROTOCOL_TYPE
{	PROTOCOL_MQTT,
	PROTOCOL_SENSTALK_V1,
	PROTOCOL_SENSTALK_V2,
	PROTOCOL_SNTP,
	PROTOCOL_HTTP,
	PROTOCOL_LORA_WAN_SENSTALK_V2,
	PROTOCOL_IOA_WEB_API,
	PROTOCOL_MAX
};

typedef enum {
#if defined PING_IP_BEFORE_CONNECT
	SOCK_PING_IP,
	SOCK_BEGIN,
#else
	SOCK_BEGIN = 0,
#endif
	SOCK_BEGIN_MQTT,
	SOCK_CREATE_WAIT,
	SOCK_CREATE_DONE,
	SOCK_CONN,
	SOCK_CONN_WAIT,
	SOCK_CONN_DONE,
	SOCK_CONN_FAIL,
	SOCK_CLOSING,
	SOCK_CLOSED,
	SOCK_IDLE,
	SOCK_MQTT_CONNECT,
	SOCK_MQTT_CONNECT_WAIT,
	SOCK_MQTT_CONNECT_DONE,
	SOCK_MAX
}SOCK_STATE;


enum HTTP_CLIENT_RSP_FSM
{	HTTP_CLIENT_RSP_FSM_IDLE,
	HTTP_CLIENT_RSP_FSM_HEADER_PARSER,
	HTTP_CLIENT_RSP_FSM_PAYLOAD_PARSER,
	HTTP_CLIENT_RSP_FSM_MAX
};

enum HTTP_CLIENT_FSM
{	HTTP_CLIENT_FSM_SEND_REQ,
	HTTP_CLIENT_FSM_WAIT_RSP,
	HTTP_CLIENT_FSM_GET_RSP,
	HTTP_CLIENT_FSM_MAX
};

enum OTA_STATE_MACHINE
{	OTA_SM_IDLE,
	OTA_SM_CHECK_VERSION,
	OTA_SM_CHECK_INFO,
	OTA_SM_DOWNLOADING,
	OTA_SM_DONE,
	OTA_SM_RUNNING,
	OTA_SM_MAX
};

enum NETWORK_TYPE
{	NETWORK_TYPE_NONE,
	NETWORK_TYPE_HS,
	NETWORK_TYPE_LS,
	NETWORK_TYPE_ETH,
	NETWORK_TYPE_MAX
};

enum SIM_AUTH
{	SIM_AUTH_NONE,
	SIM_AUTH_PAP,
	SIM_AUTH_CHAP,
	SIM_AUTH_MAX
};

enum TIME_LAPSE_UPLOAD_SERVER_TYPE
{	TIME_LAPSE_UPLOAD_SERVER_TYPE_TAIWAN,
	TIME_LAPSE_UPLOAD_SERVER_TYPE_INDONESIA,
	TIME_LAPSE_UPLOAD_SERVER_TYPE_MAX
};

enum IMG_UPLOAD_FSM
{	IMG_UPLOAD_FSM_IDLE,
	IMG_UPLOAD_FSM_PREPARE,
	IMG_UPLOAD_FSM_SEND,
	IMG_UPLOAD_FSM_WAIT_RSP,
	IMG_UPLOAD_FSM_SEND_DONE,
	IMG_UPLOAD_FSM_DELETE_FILE,
	IMG_UPLOAD_FSM_STATE_CHANGE,
	IMG_UPLOAD_FSM_MAX
};

#endif
