#ifndef __SYS_ENUM_H__
#define __SYS_ENUM_H__

/*******************
 *   config file   *
 *******************/
enum SYS_CFG_PSM
{	SYS_CFG_PSM_NONE,
	SYS_CFG_PSM_NORMAL,
	SYS_CFG_PSM_ADVANCE,
	SYS_CFG_PSM_MAX
};
 
enum ON_BOARD_PQ_ENUM
{	ON_BOARD_PQ_AI_CURRENT_0,	//0, SINGLE-END, DIFFERENTIAL
	ON_BOARD_PQ_AI_CURRENT_1,	//1, SINGLE-END, DIFFERENTIAL
	ON_BOARD_PQ_AI_CURRENT_2,	//2, SINGLE-END, DIFFERENTIAL
	ON_BOARD_PQ_AI_VOLT_0,		//3, SINGLE-END
	ON_BOARD_PQ_AI_VOLT_1,		//4, SINGLE-END
	ON_BOARD_PQ_EMPTY_IDX_5,	//5, SINGLE-END
	ON_BOARD_PQ_EMPTY_IDX_6,	//6, SINGLE-END
	ON_BOARD_PQ_EMPTY_IDX_7,	//7, reserved for Align
	
	ON_BOARD_PQ_DI_COUNTER_0,	//8
	ON_BOARD_PQ_DI_COUNTER_1,	//9
	ON_BOARD_PQ_DI_COUNTER_2,	//10, reserved for DIx
	ON_BOARD_PQ_DI_COUNTER_3,	//11, reserved for DIx
	ON_BOARD_PQ_EMPTY_IDX_12,	//12, reserved for DIx
	ON_BOARD_PQ_EMPTY_IDX_13,	//13, reserved for DIx
	ON_BOARD_PQ_EMPTY_IDX_14,	//14, reserved for Align
	ON_BOARD_PQ_EMPTY_IDX_15,	//15, reserved for Align
	
	ON_BOARD_PQ_DI_STS_0,		//16
	ON_BOARD_PQ_DI_STS_1,		//17
	ON_BOARD_PQ_DI_STS_2,		//18, reserved for DIx
	ON_BOARD_PQ_DI_STS_3,		//19
	ON_BOARD_PQ_EMPTY_IDX_20,	//20
	ON_BOARD_PQ_EMPTY_IDX_21,	//21
	ON_BOARD_PQ_EMPTY_IDX_22,	//22, reserved for Align
	ON_BOARD_PQ_EMPTY_IDX_23,	//23, reserved for Align
	
	ON_BOARD_PQ_DO_STS_0,		//24, SINK/SOURCE
	ON_BOARD_PQ_DO_STS_1,		//25, SINK/SOURCE
	ON_BOARD_PQ_EMPTY_IDX_26,	//26, reserved for DO Sink or Source
	ON_BOARD_PQ_EMPTY_IDX_27,	//27, 
	ON_BOARD_PQ_EMPTY_IDX_28,	//28
	ON_BOARD_PQ_EMPTY_IDX_29,	//29
	ON_BOARD_PQ_DO24_STS,		//30, reserved for Align
	ON_BOARD_PQ_EMPTY_IDX_31,	//31, reserved for Align
	
	ON_BOARD_PQ_ERROR_CODE,		//32
	ON_BOARD_PQ_TEMPERATURE,	//33
	ON_BOARD_PQ_BATTERY_VOLT,	//34
	ON_BOARD_PQ_EXT_VOLT,		//35
	ON_BOARD_PQ_SOLAR_CHARGE_CURRENT,	//36
	//ON_BOARD_PQ_SOLAR_CHARGE_STS,		//37
	ON_BOARD_PQ_LOAD_CURRENT,		//37
	ON_BOARD_PQ_LTE_STS,		//38
	ON_BOARD_PQ_LTE_SIGNAL_STRENGTH,	//39
	ON_BOARD_PQ_NB_STS,					//40
	ON_BOARD_PQ_NB_SIGNAL_STRENGTH,		//41
	ON_BOARD_PQ_REBOOT_TIMES,			//42
	ON_BOARD_PQ_LATITUDE,				//43
	ON_BOARD_PQ_LONGITUDE,				//44
	ON_BOARD_PQ_GPS_STATUS,				//45
	ON_BOARD_PQ_GPS_SPEED,				//46
	//need add load current
	ON_BOARD_PQ_MAX
};

/*
 * power manager IC action ID
 */
enum PWR_MNG_IC_ACTION_ID
{	PWR_MNG_IC_ACTION_ID_IDLE,
	PWR_MNG_IC_ACTION_ID_READ_TIME,
	PWR_MNG_IC_ACTION_ID_WRITE_WAKEUP_TIME,
	PWR_MNG_IC_ACTION_ID_READ_WAKEUP_TIME,
	PWR_MNG_IC_ACTION_ID_RESET,
	PWR_MNG_IC_ACTION_ID_MAX	 
};
 
enum COMMUNICATION_PRIORITY
{	COMM_PRIO_LAN_NONE = 0,
	COMM_PRIO_WIRE_LAN,
	COMM_PRIO_WIRELESS_LAN,
	COMM_PRIO_MAX
};

enum LOGIN_ID
{	LOGIN_ID_ADMIN,
	LOGIN_ID_GUEST,
	LOGIN_ID_SU,
	LOGIN_ID_INVALID,
	LOGIN_ID_MAX
};

enum STD_ARRAY_TYPE
{	STD_ARRAY_TYPE_FLOAT,
	STD_ARRAY_TYPE_INT32,
	STD_ARRAY_TYPE_UINT32,
	STD_ARRAY_TYPE_INT16,
	STD_ARRAY_TYPE_UINT16,
	STD_ARRAY_TYPE_INT8,
	STD_ARRAY_TYPE_UINT8,
	STD_ARRAY_TYPE_MAX
};

enum WEB_CAM_CAPTURE_FSM
{	WEB_CAM_CAPTURE_FSM_IDLE,
	WEB_CAM_CAPTURE_FSM_TRIG_CAPTURE,
	WEB_CAM_CAPTURE_FSM_WAIT_CAP_DONE,
	WEB_CAM_CAPTURE_FSM_UPLOAD_TO_WEB,
	WEB_CAM_CAPTURE_FSM_WAIT_WEB_UPLOAD_DONE,
	WEB_CAM_CAPTURE_FSM_TIMEOUT,
	WEB_CAM_CAPTURE_FSM_MAX
};

enum WEB_CAM_CAPTURE_MODE
{	WEB_CAM_CAPTURE_MODE_ONLY_CAP,
	WEB_CAM_CAPTURE_MODE_CAP_UPLOAD,
	WEB_CAM_CAPTURE_MODE_MAX
};

enum WEB_CAM_CAPTURE_STS
{	CWS_STS_IDLE,
	CWS_STS_TRIG,
	CWS_STS_RUNNING,
	CWS_STS_DONE,
	CWS_STS_TIMEOUT,
	CWS_STS_WRITE_FAIL,
	CWS_STS_BUF_FULL,
	CWS_STS_ERROR,
	CWS_STS_MAX
};

enum ALERT_FSM
{	ALERT_FSM_IDLE,
	ALERT_FSM_CHK_ALERT,
	ALERT_FSM_ALERT_START,
	ALERT_FSM_ALERT_POLLING,
	ALERT_FSM_ALERT_STOP,
	ALERT_FSM_ALERT_WAIT_FINAL_SEND,
	ALERT_FSM_ALERT_FINAL_SEND_DONE,
	ALERT_FSM_MAX
};

enum SET_DO_FLAG
{	SET_DO_STS,
	SET_DO_PWR,
	SET_DO_BOTH,
	SET_DO_MAX
};

enum AI_TYPE
{	AI_TYPE_4_20MA,
	AI_TYPE_0_20MA,
	AI_TYPE_20MA_BIPOLAR,
	AI_TYPE_500MV,
	AI_TYPE_5V,
	AI_TYPE_10V,
	AI_TYPE_6V_BIPOLAR,
	AI_TYPE_MAX
};

enum OTA_FLAG
{	OTA_FLAG_IDLE,
	OTA_FLAG_TRIG,
	OTA_FLAG_RUNNING,
	OTA_FLAG_FINISH,
	OTA_FLAG_MAX
};

#endif
