#ifndef __TASK_DEF_H__
#define __TASK_DEF_H__

#include "sensminiCfg.h"

enum task_define
{	SDCARD_TASK = 1,
	MAIN_TASK,
	SERV_CMD_PROCESS_TASK,
	NETWORK_PROCESS_TASK,
	NETWORK_RECV_TASK,
	MOBILE_RECV_TASK,
	MQTT_TASK, 
	UVC_CAMERA_TASK,
	NETWORK_TASK,
	CMUX_TASK,
	SENSORS_TASK,
#if SUPPORT_NUVOTON_USB_HOST
	USB_HOST_TASK,
#endif
	EXPANDER_TASK,
	TASK_MAX
};


#if defined OS_FREERTOS

	
#define MAX_TASK_PRIORITY							configMAX_PRIORITIES

#define LOWEST_PRIORITY								0
#define LOWER_PRIORITY								1
#define LOW_PRIORITY								2
#define NORMAL_PRIORITY								3
#define HIGH_PRIORITY								4
#define HIGHER_PRIORITY								5
#define HIGHEST_PRIORITY							6

	#if defined SENSMINIA4_PRO || defined SENSMINIA4_NEO
#define MQTT_TASK_PRIORITY							7
#define SENSORS_TASK_PRIORITY						6
#define NETWORK_PROCESS_TASK_PRIORITY 				9
#define NETWORK_RECV_TASK_PRIORITY 					9
#define MOBILE_RECV_TASK_PRIORITY 					10
#define SERV_CMD_PROCESS_TASK_PRIORITY 				11
#define CMUX_TASK_PRIORITY							2
//#define CMUX_TASK_PRIORITY						14
#define MAIN_TASK_PRIORITY 							17
#define SDCARD_TASK_PRIORITY 						13

#define USB_HOST_TASK_PRIORITY						12

#define MODBUS_TASK_PRIORITY						4
#define PPPOS_RX_THREAD_PRIORITY					14	//not use

#define LWIP_DEFAULT_PRIORITY						19
#define TPCIP_TASK_PRIORITY							20

#define ETH_RX_THREAD_PRIO                  		15
//#define TPCIP_TASK_PRIORITY						15
#define HTTP_SERVER_TASK_PRIORITY					16
#define UVC_CAMERA_TASK_PRIORITY					22
#define EXPANDER_TASK_PRIORITY						31	//need highest priority


#define MQTT_TASK_STACK_SIZE						4096
#define SENSORS_TASK_STACK_SIZE						4096
#define NETWORK_PROCESS_TASK_STACK_SIZE				16384
#define NETWORK_RECV_TASK_STACK_SIZE				8192
#define MOBILE_RECV_TASK_STACK_SIZE					4096
#define SERV_CMD_PROCESS_TASK_STACK_SIZE			8192
#define MAIN_TASK_STACK_SIZE						8192
#define SDCARD_TASK_STACK_SIZE						4096
#define CMUX_TASK_STACK_SIZE						4096
#define USB_HOST_TASK_STACK_SIZE					4096	
#define ETH_RX_THREAD_STACKSIZE             		8192
#define UVC_CAMERA_TASK_STACKSIZE					4096
#define EXPANDER_TASK_STACKSIZE						1024	

	#endif	//endof #ifdef SENSMINIA4_PRO


	#ifdef SENSMINIS2
	
#define MQTT_TASK_PRIORITY							7
#define SENSORS_TASK_PRIORITY						6
#define NETWORK_SEND_TASK_PRIORITY 					9
#define NETWORK_RECV_TASK_PRIORITY 					9
#define MOBILE_RECV_TASK_PRIORITY 					10
#define SENSTALK_TASK_PRIORITY 						11
#define CMUX_TASK_PRIORITY							2
//#define CMUX_TASK_PRIORITY						14
#define MAIN_TASK_PRIORITY 							13
#define SDCARD_TASK_PRIORITY 						15

#define USB_HOST_TASK_PRIORITY						12

#define MODBUS_TASK_PRIORITY						4
#define PPPOS_RX_THREAD_PRIORITY					14	//not use

#define LWIP_DEFAULT_PRIORITY						2
#define TPCIP_TASK_PRIORITY							3
//#define TPCIP_TASK_PRIORITY						15

#define MQTT_TASK_STACK_SIZE						2048
#define SENSORS_TASK_STACK_SIZE						2048
#define NETWORK_SEND_TASK_STACK_SIZE				2048
#define NETWORK_RECV_TASK_STACK_SIZE				2048
#define MOBILE_RECV_TASK_STACK_SIZE					2048
#define SENSTALK_TASK_STACK_SIZE					2048
#define MAIN_TASK_STACK_SIZE						2048
#define SDCARD_TASK_STACK_SIZE						2048
#define CMUX_TASK_STACK_SIZE						2048
#define USB_HOST_TASK_STACK_SIZE					2048
	#endif	//endof #ifdef SENSMINIS2


extern void mainTask(void *param);

#elif defined OS_MQX

extern void mainTask(uint32_t param);
#endif


/*
*	MSG Q
*/
enum SERV_CMD_PROCESS_Q_TASK_MSG
{	SERV_CMD_PROCESS_Q_MSG_SEND_CMD = 0x00004000,
	SERV_CMD_PROCESS_Q_MSG_RECV_CMD,
	//FOTA_Q_MSG_GET_FILE_START = 0x00004200,
	//FOTA_Q_MSG_GET_FILE_TO_SPI,
	SERV_CMD_PROCESS_Q_MSG_MAX
};

enum SENSOR_TASK_MSG
{	SENSOR_Q_MSG_GET_NORMAL_SENSOR_VALUE = 0x00007000,	//Temperature, charg Status, adc volt...
	SENSOR_Q_MSG_GET_AI_SENSOR,
	SENSOR_Q_MSG_CAMERA_PRE_START,
	SENSOR_Q_MSG_CAMERA_INIT_TIMEOUT,
	SENSOR_Q_MSG_CAMERA_START,
	/*SENSOR_Q_MSG_CAMERA_WAIT_RDY,
	SENSOR_Q_MSG_CAMERA_CHK_AND_SET_BAUDRATE,	//test auto baudrate function
	SENSOR_Q_MSG_CAMERA_CHG_RESOLUTION,
	SENSOR_Q_MSG_CAMERA_IR_ON,
	SENSOR_Q_MSG_CAMERA_CHG_QUALITY,
	SENSOR_Q_MSG_CAMERA_RESET,
	SENSOR_Q_MSG_CAMERA_CATCH_IMG,
	SENSOR_Q_MSG_CAMERA_GET_IMG_SIZE,*/
	SENSOR_Q_MSG_CAMERA_GET_IMG_DATA,
	SENSOR_Q_MSG_CAMERA_STOP,
	SENSOR_Q_MSG_SAVE_IMG_FILE,
	SENSOR_Q_MSG_UPLOAD_IMAGE_PREPARE,
	SENSOR_Q_MSG_MAX
};
	
enum NETWORK_TASK_MSG
{	NETWORK_Q_MSG_SEND_CMD  = 0x00008000,
	NETWORK_Q_MSG_TCP_INIT,
	NETWORK_Q_MSG_TCP_SOCK_CREATE,
	NETWORK_Q_MSG_TCP_SOCK_CONNECT,
	NETWORK_Q_MSG_TCP_STOP,
	NETWORK_Q_MSG_NETWORK_PRE_INIT,
	NETWORK_Q_MSG_NETWORK_INIT,
	NETWORK_Q_MSG_WIRE_LAN_LINK_UP,
	NETWORK_Q_MSG_LAN_DEINIT,
	NETWORK_Q_MSG_LAN_DESTROY,
	NETWORK_Q_MSG_WIRE_LAN_RECV_TASK_DELETE,
	NETWORK_Q_MSG_PPP_DISCONNECTED,
	NETWORK_Q_MSG_HTTP_POST,
	NETWORK_Q_MSG_HTTP_POST_TIMEOUT,
	NETWORK_Q_MSG_HTTP_POST_DONE,
	NETWORK_Q_MSG_HTTP_GET,
	NETWORK_Q_MSG_HTTP_GET_TIMEOUT,
	NETWORK_Q_MSG_HTTP_GET_DONE,
	NETWORK_Q_MSG_MOBILE_AT_CMD_NORMAL_RSP,
	NETWORK_Q_MSG_MOBILE_UREG_GET,
	NETWORK_Q_MSG_MOBILE_CSQ_GET,
#if SUPPORT_AGPS
	NETWORK_Q_MSG_AGPS_LOCATION_GET,
	NETWORK_Q_MSG_AGPS_LOCATION_GET_ONCE,
#endif
#if SUPPORT_IOA_WEB_API
	NETWORK_Q_MSG_IOA_GET_TOKEN,
	NETWORK_Q_MSG_IOA_SEND_DATA,
	NETWORK_Q_MSG_IOA_RSP,
#endif
	NETWORK_Q_MSG_MAX
};

enum MQTT_TASK_MSG
{	MQTT_Q_MSG_CREATE_SOCK_CONNECT = 0x00009000,
	MQTT_Q_MSG_MQTT_CONNECT,
	MQTT_Q_MSG_MQTT_CONNECT_WAIT,
	MQTT_Q_MSG_MQTT_SUB,
	MQTT_Q_MSG_POLLING,
	MQTT_Q_MSG_PING,
	MQTT_Q_MSG_PUBLISH,
	MQTT_Q_MSG_DISCONNECT,
	MQTT_Q_MSG_EMPTY,
	MQTT_Q_MSG_MAX
};

enum SD_TASK_MSG
{	SD_Q_MSG_GET_FILE_LENGTH = 0x0000A000,
	SD_Q_MSG_READ,
	SD_Q_MSG_WRITE,
	SD_Q_MSG_CREATE_DIR,
	SD_Q_MSG_CHK_FILE_EXIST,
	SD_Q_MSG_DELETE_FILE,
	SD_Q_MSG_CREATE_JPG_FILE,
	SD_Q_MSG_WRITE_LOG,
	SD_Q_MSG_PARSER_INI_FILE, 
	SD_Q_MSG_SAVE_INI_FILE,
	SD_Q_MSG_MAX
};

enum USB_HOST_TASK_MSG
{	USBH_Q_MSG_SERIAL_STATE_NOTIFY = 0x0000B000,
	USBH_Q_MSG_SERIAL_STATE_ERROR, 
	USBH_Q_MSG_CDC_ACM_COMPOSITE_DEV_CONNECT,
	USBH_Q_MSG_CDC_ACM_COMPOSITE_DEV_DISCONNECT,
	USBH_Q_MSG_CDC_ECM_DEV_CONNECT,
	USBH_Q_MSG_CDC_ECM_DEV_DISCONNECT,
	USBH_Q_MSG_CDC_ECM_NET_LINKUP,
	USBH_Q_MSG_CDC_ECM_NET_LINKDOWN,
	USBH_Q_MSG_CDC_ECM_SPEED_CHANGED,
	USBH_Q_MSG_CDC_ECM_GET_STATUS,
	USBH_Q_MSG_SET_WLINST,
	USBH_Q_MSG_MAX
};

enum EXPANDER_TASK_MSG
{	EXPANDER_Q_MSG_IRQ_ACT = 0x0000C000,
	EXPANDER_Q_MSG_MAX
};

enum TASK_WORKING_STATUS
{	TASK_STS_INITIAL,	//task initial
	TASK_STS_RUNNING,	//running msgQ
	TASK_STS_BLOCKED,	//watting for msgQ
	TASK_STS_ABORT		//task abort
};


#endif